name: Sphinx-build-html

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone my repo
      uses: actions/checkout@v2
    - name: Install Sphinx
      run: |
       pip install -U Sphinx
       pip install sphinx_rtd_theme
       sphinx-build --version
    - name: Build HTML
      run: |
       sphinx-build -b html source build
       tree -L 3
       pwd
       ls -al
    - name: Dependency
      run: echo furo==2021.11.16 > requirements.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: build        
    - name: Push and send notification
      run: |
          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          # Only if repo have changes
          git commit -m "${COMMIT_MESSAGE}"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git main
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
